# Generated by Django 4.1.7 on 2023-03-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_post_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
