# Generated by Django 4.1.7 on 2023-03-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_blog_post_body_alter_blog_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=models.ImageField(blank=True, default='add Item image', upload_to='get_upload_file_name'),
        ),
    ]
